export interface Restriction {
  /**
   * An UUID auto-generated by the database
   */
  id: string;
  /**
   * A foreign key to the discount table item that this restriction belongs to
   */
  discountId: string;
  /**
   * A foreign key to the product table item that this restriction belongs to
   */
  productId: string;
  /**
   * The range specifies the number of items that must be purchased to qualify for the discount.
   * The first element is the lower bound and the second element is the upper bound.
   * Null means there is no restriction on that bound.
   */
  range: [number | null, number | null];
}
