/**
 * The RestrictionModel interface represents the criteria that must be met for discounts in the DISCOUNTS table to apply.
 * The restriction is a many-to-one relationship with the DISCOUNTS table. (Many restrictions per discount)
 * It also is a one-to-one relationship with the PRODUCTS table. (One restriction per product)
 *
 * For discounts that require multiple restrictions for multiple products, multiple rows are added to the RESTRICTIONS table.
 */
export interface RestrictionModel {
  /**
   * An UUID auto-generated by the database
   */
  id: string;
  /**
   * The UUID of the discount that this restriction applies to.
   */
  discount_id: string;
  /**
   * The product that this restriction applies to.
   * Eg., productId = ABC, range = [1, 3].
   * This means that if the customer buys 1 to 3 of product ABC, they qualify for the discount.
   */
  product_id: string;
  /**
   * The range in which the customer must buy the product to qualify for the discount.
   * Range is a string representing a SQL NUMRANGE.
   */
  range: string;
  /**
   * The name of the product that this restriction applies to.
   * Retrieved from the products table.
   */
  product_name: string;
}
