openapi: 3.0.0
info:
  title: Shopping Cart
  version: 1.0.0
servers:
  - url: http://{{baseurl}}
paths:
  /products:
    get:
      tags:
        - default
      summary: Retrieve products
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /discounts:
    get:
      tags:
        - default
      summary: Retrieve discounts
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /orders:
    get:
      tags:
        - default
      summary: Retrieve orders
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /orders/{id}:
    get:
      tags:
        - default
      summary: Retrieve orders by ID
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 34ce4cd3-52ec-4996-9265-ba917044fb4f
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /orders/{orderId}/items/{itemId}:
    get:
      tags:
        - default
      summary: Retrieve order item by order ID and item ID
      parameters:
        - name: orderId
          in: path
          schema:
            type: string
          required: true
          example: 579fa14b-263e-4bef-b695-15a98d5a940c
        - name: itemId
          in: path
          schema:
            type: integer
          required: true
          example: '234234'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /orders/:
    post:
      tags:
        - default
      summary: Create order
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                items:
                  - product_id: 120P90
                    quantity: 3
                  - product_id: 43N23P
                    quantity: 1
                  - product_id: '234234'
                    quantity: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /orders/{id}/checkout:
    post:
      tags:
        - default
      summary: Checkout order
      requestBody:
        content: {}
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 22f1315d-7d29-47ac-809e-58a2db19272e
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /orders/{id}/add:
    post:
      tags:
        - default
      summary: Add items to order by ID
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                items:
                  - product_id: '234234'
                    quantity: 1
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 22f1315d-7d29-47ac-809e-58a2db19272e
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
